apiVersion: v1
kind: ConfigMap
metadata:
  name: dbs2go-filebeat-config
  namespace: dbs
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /data/logs/*${MY_POD_NAME}*
      ignore_older: 1h
      scan_frequency: 10s
      backoff: 5s
      max_backoff: 10s
    output.console:
      codec.format:
        string: '%{[message]} - Podname=${MY_POD_NAME}'
        pretty: false
    queue.mem:
      events: 65536
    logging.metrics.enabled: false
---
kind: Service
apiVersion: v1
metadata:
  name: dbs2go-server
  namespace: dbs
spec:
  selector:
    app: dbs2go-server
  ports:
  - port: 8258
    targetPort: 8258
    name: dbs
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: dbs2go-server
  name: dbs2go-server
  namespace: dbs
spec:
  selector:
    matchLabels:
      app: dbs2go-server
  replicas: 1
  template:
    metadata:
      labels:
        app: dbs2go-server
        env: k8s #k8s#
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: "/dbs2go/metrics"
        prometheus.io/port: "8258"
    spec:
      containers:
      - image: registry.cern.ch/cmsweb/dbs2go-server #imagetag
        name: dbs2go-server
        imagePullPolicy: Always
        env:
        - name: X509_USER_PROXY
          value: /etc/proxy/proxy
        - name: LD_LIBRARY_PATH
          value: /usr/lib/oracle
        command:
        - /data/dbs2go
        - -config
        - /etc/secrets/dbsconfig.json
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "500Mi"
            cpu: "8000m"
        livenessProbe:
          httpGet:
            path: /dbs2go/healthz
            port: 8258
            httpHeaders:
            - name: Accept
              value: application/json
          initialDelaySeconds: 120
          periodSeconds: 10
        ports:
        - containerPort: 8258
          protocol: TCP
          name: dbs
        volumeMounts:
        - name: proxy-secrets
          mountPath: /etc/proxy
          readOnly: true
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
        - name: robot-secrets
          mountPath: /etc/robots
          readOnly: true
        - name: hmac-secrets
          mountPath: /etc/hmac
          readOnly: true
        - name: tnsnames-ora
          mountPath: /etc/tnsnames.ora # This should be your final destination
          subPath: tnsnames.ora # The name of the file to be placed inside /etc

      volumes:
      - name: proxy-secrets
        secret:
          secretName: proxy-secrets
      - name: secrets
        secret:
          secretName: dbs2go-secrets
      - name: robot-secrets
        secret:
          secretName: robot-secrets
      - name: hmac-secrets
        secret:
          secretName: hmac-secrets
      - name: tnsnames-ora
        configMap:
          name: tnsnames-ora
        # mountPath: /etc/tnsnames.ora # This should be your final destination
# subPath: tnsnames.ora # The name of the file to be placed inside /etc
