#!/bin/bash

mariadbRoot=root
mariadbRootPass=fixme
mariadbUser=cmst1
mariadbUserPass=fixme

configDir=/data/srv/mariadb/current/config
dataDir=/data/srv/mariadb/current/install/database
logDir=/data/srv/mariadb/current/logs
socket=/data/srv/mariadb/current/mariadb.sock
agentDb=wmagent

help(){
    echo -e $*
    cat <<EOF

The manage script of the MariaDB docker image for WMAgent

Usage: manage  status | start-mariadb | stop-mariadb | clean-mariadb | db-prompt | version

EOF
}

usage(){
    help $*
    exit 1
}

status(){
    mariadb-admin --socket=$socket status
}

start_mariadb(){
    echo starting MariaDB server
    mariadbd-safe --defaults-extra-file=$configDir/my.cnf \
                  --datadir=$dataDir \
                  --log-bin \
                  --socket=$socket \
                  --log-error=$logDir/error.log \
                  --pid-file=$logDir/mariadbd.pid  &
    echo ...
    sleep 10
    echo status
}

stop_mariadb(){
    mariadb-admin --socket=$socket shutdown
}

db_prompt(){
    mariadb --socket=$socket --database=$wmaDBName --pager='less -SFX'
}

clean_mariadb(){
    db_prompt "drop database $wmaDBName"
}

version(){
    mariadb-admin --socket=$socket version
}

case $1 in
  status)
      status ;;
  start-mariadb)
      start_mariadb;;
  stop-mariadb)
      stop_mariadb;;
  clean-mariadb)
      clean_mariadb;;
  db-prompt)
      shift
      db_prompt $@;;
  version)
      version ;;
  help)
      help ;;
  *)
      usage ;;
esac
