#!/bin/bash

#### These are old mysql actions previously defined in the wmagent manage script
#### Some of them need to be rewritten some of them must go away



# #########################
# #  MySQL                #
# #########################

# #
# # first time startup routines for mysql
# # pre gets called before startup, post called after it
# init_mysql_db_pre(){
#     echo "Installing the mysql database area..."
#     mkdir -p $INSTALL_MYSQL/database
#     mkdir -p $INSTALL_MYSQL/logs
#     mysql_install_db --datadir=$INSTALL_MYSQL/database
# }
# init_mysql_db_post(){
#     #install the WMAgent stuff
#     echo "Installing the mysql schema..."
#     load_secrets_file;
#     local TIMEOUT=0;
#     while [ ! -e $MYSQL_SOCK ]
#     do
#         sleep 2;
#         TIMEOUT=$(($TIMEOUT+2))
#         if [ $TIMEOUT -ge 300 ]; then
#             echo "ERROR: Timeout waiting for mysqld to start."
#             exit 1;
#         fi
#     done
#     echo "Socket file exists, proceeding with schema install..."

#     inited_mysql;

#     # create a user - different than root and current unix user - and grant privileges
#     if [ "$MYSQL_USER" != "$USER" ]; then
#         mysql -u $USER --socket=$MYSQL_SOCK --execute "CREATE USER '${MYSQL_USER}'@'localhost'"
#         mysql -u $USER --socket=$MYSQL_SOCK --execute "GRANT ALL ON *.* TO $MYSQL_USER@localhost WITH GRANT OPTION"
#     fi

#     # create databases for agent
#     if [ $USING_AG -eq 1 ]; then
#         echo "Installing WMAgent Database: ${MYSQL_DATABASE_AG}"
#         mysql -u $USER --socket=$MYSQL_SOCK --execute "create database ${MYSQL_DATABASE_AG}"
#     fi
# }

# status_of_mysql(){
#     load_secrets_file;
#     if [ "x$MYSQL_USER" == "x" ]; then
# 	echo "Not using MySQL..."
# 	exit 1;
#     fi

#     echo "+ Status of MySQL"
#     if [ ! -e $INSTALL_MYSQL/logs/mysqld.pid ]; then
#         echo "++ MySQL process file not found"
#         return
#     fi
#     local MYSQL_PID=`cat $INSTALL_MYSQL/logs/mysqld.pid`
#     kill -0 $MYSQL_PID;
#     local MYSQL_STATUS=$?
#     if [ $MYSQL_STATUS -eq 0 ]; then
#         echo "++ MYSQL running with process: $MYSQL_PID";
#     else
#         echo "++ MYSQL process not running"
#     fi

#     echo "++" `mysqladmin -u $MYSQL_USER --socket=$MYSQL_SOCK status`
# }

# #
# # Main startup method for MySQL.
# # Checks for initialisation
# start_mysql(){
#     load_secrets_file;
#     if [ "x$MYSQL_USER" == "x" ]; then
# 	    echo "Not using MySQL..."
# 	    exit 1;
#     fi

#     echo "Starting mysql..."

#     if [ $MYSQL_INIT_DONE -eq 0 ]; then
# 	    echo "MySQL has not been initialised... running pre initialisation";
# 	    init_mysql_db_pre;
#     fi

#     # Start mysqld to install the database schemas
#     #
#     echo "starting mysqld_safe..."
#     nohup mysqld_safe --defaults-extra-file=$CONFIG_MYSQL/my.cnf \
#                       --datadir=$INSTALL_MYSQL/database \
#                       --log-bin \
#                       --socket=$MYSQL_SOCK \
#                       --log-error=$INSTALL_MYSQL/logs/error.log \
#                       --pid-file=$INSTALL_MYSQL/logs/mysqld.pid > /dev/null 2>&1 < /dev/null &
#     local TIMEOUT=0;
#     echo "Checking MySQL Socket file exists..."
#     while [ ! -e $MYSQL_SOCK ]
#       do
#       sleep 2;
#       TIMEOUT=$(($TIMEOUT+2))
#       if [ $TIMEOUT -ge 300 ]; then
# 	    echo "ERROR: Timeout waiting for mysqld to start."
# 	    exit 1;
#       fi
#     done
#     echo "Socket file exists: $MYSQL_SOCK"

#     if [ $MYSQL_INIT_DONE -eq 0 ]; then
#         echo "MySQL has not been initialised... running post initialisation";
#         init_mysql_db_post;
#     fi
#     echo "Checking Server connection..."
#     mysql -u $USER --socket=$MYSQL_SOCK --execute "SHOW GLOBAL STATUS" > /dev/null;
#     if [ $? -ne 0 ]; then
# 	    echo "ERROR: checking mysql database is running, failed to execute SHOW GLOBAL STATUS"
# 	    exit 1
#     fi
#    echo "Connection OK"
# }

# #
# # stop MySQL
# #
# stop_mysql(){
#     load_secrets_file;
#     if [ "x$MYSQL_USER" == "x" ]; then
# 	echo "Not using MySQL..."
# 	exit 1;
#     fi

#     echo "stopping mysql..."
#     mysqladmin -u $MYSQL_USER --socket=$MYSQL_SOCK shutdown &
#     wait $!
#     echo "Making sure the MySQL socket file is removed..."
#     local TIMEOUT=0;
#     while [ -e $MYSQL_SOCK ]
#       do
#       sleep 2;
#       TIMEOUT=$(($TIMEOUT+2))
#       if [ $TIMEOUT -ge 300 ]; then
# 	  echo "ERROR: Timeout waiting for mysqld to shutdown."
# 	  echo "ERROR: Socket file still exists: $MYSQL_SOCK"
# 	  exit 1;
#       fi
#     done
#     echo "MySQL is shutdown."
# }

# #

# case $1 in
#   status)
#     status ;;
#   start-mysql)
#     start_mysql;;
#   stop-mysql)
#     stop_mysql;;
#   clean-mysql)
#      clean_mysql;;
#   db-prompt)
#      db_prompt $@;;
#   mysql-prompt)
#      db_prompt $@;;
#   help)
#     help ;;
#   version)
#     echo "Management script for WMAgent. No idea what version, at least 2 though" ;;
#   * )
#     echo "$0: unknown action '$1', please try '$0 help' or documentation." 1>&2
#     exit 1 ;;
# esac
