apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: crabserver-hpa
  namespace: crab
spec:
  maxReplicas: 10
  minReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: crabserver # deployment name
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 200
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 300
