{{- if .Values.ciServiceAccount.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: crab-gitlab-ci
  name: crab-gitlab-ci-secret
  labels:
    {{- include "crabserver.labels" . | nindent 4 }}
type: kubernetes.io/service-account-token
{{- end }}