{{- if .Values.ciServiceAccount.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crab-ns-full-access
  namespace: crab
subjects:
- kind: ServiceAccount
  name: crab-gitlab-ci
  namespace: crab
roleRef:
  kind: Role
  name: crab-ns-full-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: crab
  name: crab-ns-full-access
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
{{- end }}
