{{- if .Values.logPipeline.enabled -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    k8s-app: filebeat
  name: filebeat-crab-config
  namespace: crab
data:
  filebeat.yml: |-
{{ (.Files.Get "config/filebeat.yml" | indent 4) }}
{{- end }}
