{{- $environment := .Values.environment | default dict }}
{{- if .Values.logPipeline.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    k8s-app: logstash
  name: logstash-crab
data:
  # logstash config
  logstash.yml: |
{{- if (eq (toString $environment) "prod") }}
{{ (.Files.Get "config/prod/logstash/logstash.yml" | indent 4) }}
{{- else if (eq (toString $environment) "preprod")}}
{{ (.Files.Get "config/preprod/logstash/logstash.yml" | indent 4) }}
{{- else }}
{{ (.Files.Get "config/test/logstash/logstash.yml" | indent 4) }}
{{- end }}
  # pipeline config
  logstash.conf: |
{{- if (eq (toString $environment) "prod") }}
{{ (.Files.Get "config/prod/logstash/logstash.conf" | indent 4) }}
{{- else if (eq (toString $environment) "preprod")}}
{{ (.Files.Get "config/preprod/logstash/logstash.conf" | indent 4) }}
{{- else }}
{{ (.Files.Get "config/test/logstash/logstash.conf" | indent 4) }}
{{- end }}

{{- end }}
