{{- if and (.Values.enabled) (.Values.serviceAccount.create)  -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crabserver.serviceAccountName" . }}
  labels:
    {{- include "crabserver.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
