{{- if and (.Values.enabled) -}}
kind: Service
apiVersion: v1
metadata:
  name: crabserver
  namespace: crab
spec:
  selector:
    app: crabserver
  ports:
    - port: 8270
      targetPort: 8270
      name: crabserver
    - port: 18270
      targetPort: 18270
      name: crabserver-mon
{{- end }}
