apiVersion: v1
kind: ServiceAccount
metadata:
  name: spider-account
  namespace: spider
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spider-account
  namespace: spider
subjects:
- kind: ServiceAccount
  name: spider-account
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
