# cpueff-spark
FROM mongo:5.0.14 as builder
FROM registry.cern.ch/cmsmonitoring/cmsmon-hadoop-base:spark3-el9-20240708
MAINTAINER Ceyhun Uzunoglu ceyhunuzngl@gmail.com

# tag to use
ARG CMSMON_TAG=cpueff-0.0.0
ENV WDIR=/data
WORKDIR $WDIR

ENV HADOOP_CONF_DIR=/etc/hadoop/conf
ENV PATH="${PATH}:${WDIR}/CMSMonitoring/cpueff-goweb/spark"
ENV PYTHONPATH "${PYTHONPATH}:${WDIR}:${WDIR}/CMSSpark/src/python:${WDIR}/CMSMonitoring/src/python:${WDIR}/CMSMonitoring/cpueff-goweb/spark"

COPY --from=builder /usr/bin/mongoimport $WDIR
COPY --from=builder /usr/bin/mongosh $WDIR

RUN mkdir -p $WDIR/logs && \
    git clone https://github.com/dmwm/CMSSpark.git &&  \
    git clone https://github.com/dmwm/CMSMonitoring.git &&  \
    cd CMSMonitoring && git checkout tags/$CMSMON_TAG -b build && cd .. && \
    zip -r CMSMonitoring.zip CMSMonitoring/src/python/CMSMonitoring/* && \
    pip install --no-cache-dir stomp.py==7.0.0 click pyspark pandas numpy schema seaborn matplotlib plotly && \
    hadoop-set-default-conf.sh analytix && source hadoop-setconf.sh analytix 3.3 spark3

WORKDIR $WDIR

# Run crond
CMD ["crond", "-n", "-s", "&"]
