# CephFS volume claims:
# for production storage use
#   storageClassName: meyrin-cephfs
# for test storage use
#   storageClassName: geneva-cephfs-testing
# ---
#
# frontend storage claim
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: affilations-cephfs-claim
  namespace: spider
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: meyrin-cephfs
