apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: monit-mongo
  labels:
    app: mongodb
spec:
  clusterIP: None
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: monit-mongo
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      namespace: monit-mongo
      labels:
        app: mongodb
        selector: mongodb
    spec:
      containers:
      - name: mongodb
        image: registry.cern.ch/cmsmonitoring/monit-mongo:5.0.9
        args: [ "--dbpath","/data/db" ]
        livenessProbe:
          exec:
            command:
              - mongo
              - --disableImplicitSessions
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
              - mongo
              - --disableImplicitSessions
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 250m
            memory: 200Mi
        env:
          - name: MONGO_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: monit-mongo-secrets
                key: MONGO_ROOT_USERNAME
                optional: false
          - name: MONGO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: monit-mongo-secrets
                key: MONGO_ROOT_PASSWORD
                optional: false
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: monit-mongo-secrets
                key: MONGO_USERNAME
                optional: false
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: monit-mongo-secrets
                key: MONGO_PASSWORD
                optional: false
          - name: MONGO_USERS_LIST
            valueFrom:
              secretKeyRef:
                name: monit-mongo-secrets
                key: MONGO_USERS_LIST
                optional: false
          - name: MONGO_INITDB_ROOT_USERNAME_FILE # Required by MongoDB
            value: /etc/secrets/MONGO_INITDB_ROOT_USERNAME_FILE
          - name: MONGO_INITDB_ROOT_PASSWORD_FILE # Required by MongoDB
            value: /etc/secrets/MONGO_INITDB_ROOT_PASSWORD_FILE
        volumeMounts:
        - name: monit-mongo-secrets
          mountPath: /etc/secrets
          readOnly: true
        - name: monit-mongo-data
          mountPath: /data/db
      volumes:
        - name: monit-mongo-secrets
          secret:
            secretName: monit-mongo-secrets
            defaultMode: 0444
        - name: monit-mongo-data
          emptyDir: {}

# References
#  - https://devopscube.com/deploy-mongodb-kubernetes/
#  - https://phoenixnap.com/kb/kubernetes-mongodb
