apiVersion: v1
kind: ConfigMap
metadata:
  name: cric-fetch-script
  namespace: auth
data:
  fetch-cric.sh: |
    #!/bin/sh
    echo "Starting CRIC fetch script..."
    odir=/etc/cric/cric.json
    tstamp=`date "+%Y%m%d_%H%M%S"`
    temp_output=/tmp/cric_output_${tstamp}.json
    
    # Run curl command and capture the HTTP status code
    response_code=$(curl --cert /etc/robots/robotcert.pem --key /etc/robots/robotkey.pem \
        -k -L -s -w "%{http_code}" \
        -o ${temp_output} "https://cms-cric.cern.ch/api/accounts/user/query/?json&preset=roles")
    
    curl_exit_code=$?

    if [ "$curl_exit_code" -eq 0 ] && [ "$response_code" -eq 200 ]; then
        mv ${temp_output} ${odir}
        echo "CRIC data fetched successfully and moved to ${odir}."
        
        # Show the head and tail of the file
        echo "=== First 10 lines of ${odir} ==="
        head -n 10 ${odir}
        
        echo "=== Last 10 lines of ${odir} ==="
        tail -n 10 ${odir}
    else
        echo "Failed to fetch CRIC data. Curl exit code: $curl_exit_code, Response code: $response_code"
        echo "Partial or error output:"
        cat ${temp_output}
    fi

    echo "\nScript completed."
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cric-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/etc/cric"  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cric-pvc
  namespace: auth
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-cric
  namespace: auth
spec:
  schedule: "0 * * * *"  # Runs every hour
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 0
          containers:
          - name: cric-fetch
            image: curlimages/curl:latest
            command: ["/bin/sh", "/script/fetch-cric.sh"]
            volumeMounts:
            - name: cric-volume
              mountPath: /etc/cric
            - name: robot-secrets
              mountPath: /etc/robots
            - name: script-volume
              mountPath: "/script"
          restartPolicy: Never
          volumes:
          - name: cric-volume
            persistentVolumeClaim:
              claimName: cric-pvc
          - name: robot-secrets
            secret:
              secretName: robot-secrets
          - name: script-volume
            configMap:
              name: cric-fetch-script
              defaultMode: 0777
