apiVersion: v1
kind: ConfigMap
metadata:
  name: cric-fetch-script
  namespace: auth
data:
  fetch-cric.sh: |
    #!/bin/sh
    echo "Starting CRIC fetch script..."
    odir=/etc/cric/cric.json
    tstamp=`date "+%Y%m%d_%H%M%S"`
    response_code=$(curl --cert /etc/robots/robotcert.pem --key /etc/robots/robotkey.pem \
        -k -L -s -w "%{response_code}" \
        "https://cms-cric.cern.ch/api/accounts/user/query/?json&preset=roles123" -o ${odir}.${tstamp})
    echo "Curl command executed with response code: $response_code"

    if [ "$?" == "0" ] && [ "$response_code" == "200" ]; then
        mv ${odir}.${tstamp} ${odir}
        echo "CRIC data fetched successfully and moved to ${odir}."
    else
        echo "Failed to fetch CRIC data or invalid response code: $response_code"
    fi

    echo "=== Head of ${odir} ==="
    head -n 10 ${odir}

    echo "=== Tail of ${odir} ==="
    tail -n 10 ${odir}
    echo "Script completed."
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cric-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/etc/cric"  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cric-pvc
  namespace: auth
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-cric
  namespace: auth
spec:
  schedule: "0 * * * *"  # Runs every hour
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 0
          containers:
          - name: cric-fetch
            image: curlimages/curl:latest
            command: ["/bin/sh", "/script/fetch-cric.sh"]
            volumeMounts:
            - name: cric-volume
              mountPath: /etc/cric
            - name: robot-secrets
              mountPath: /etc/robots
            - name: script-volume
              mountPath: "/script"
          restartPolicy: Never
          volumes:
          - name: cric-volume
            persistentVolumeClaim:
              claimName: cric-pvc
          - name: robot-secrets
            secret:
              secretName: robot-secrets
          - name: script-volume
            configMap:
              name: cric-fetch-script
              defaultMode: 0777
