apiVersion: v1
kind: ServiceAccount
metadata:
  name: cric-account
  namespace: auth
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cric-account
  namespace: auth
subjects:
- kind: ServiceAccount
  name: cric-account
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
