apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor-account
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monitor-account
subjects:
- kind: ServiceAccount
  name: monitor-account
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
