kind: Service
apiVersion: v1
metadata:
  name: cmsmon-rucio-spark2mng
  namespace: datasetmon
spec:
  selector:
    app: cmsmon-rucio-spark2mng
  type: NodePort
  ports:
    - name: port-0 # spark.driver.port, cern default is 5201
      nodePort: 31203
      port: 31203
      protocol: TCP
      targetPort: 31203
    - name: port-1 # spark.driver.blockManager.port
      nodePort: 31204
      port: 31204
      protocol: TCP
      targetPort: 31204
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-cmsmon-rucio-spark2mng
  namespace: datasetmon
  labels:
    app: cmsmon-rucio-spark2mng
data:
  createindexes.js: |
    // switch to rucio db
    use rucio;
    // datasets indexes
    db.datasets.createIndex( { "_id": 1, "Dataset": 1 } );
    db.datasets.createIndex( { "Dataset": 1 } );
    db.datasets.createIndex( { "LastAccessMs": 1 } );
    db.datasets.createIndex( { "Max": 1 } );
    db.datasets.createIndex( { "Min": 1 } );
    db.datasets.createIndex( { "Avg": 1 } );
    db.datasets.createIndex( { "Sum": 1 } );
    db.datasets.createIndex( { "RealSize": 1 } );
    db.datasets.createIndex( { "TotalFileCnt": 1 } );
    db.datasets.createIndex( { "RseType": "text", "Dataset": "text", "RSEs": "text"} );
    // detailed_datasets indexes
    db.detailed_datasets.createIndex( { "_id": 1, "Type": 1 } );
    db.detailed_datasets.createIndex( { "_id": 1, "Dataset": 1 } );
    db.detailed_datasets.createIndex( { "_id": 1, "Dataset": 1, "RSE":1 } );
    db.detailed_datasets.createIndex( {"Dataset": 1} );
    db.detailed_datasets.createIndex( { "Dataset": 1, "RSE":1 } );
    db.detailed_datasets.createIndex( { "Type": "text", "Dataset": "text", "RSE": "text", "Tier": "text", "C": "text", "RseKind": "text","ProdAccts": "text"} );
  run.sh: |
    #!/bin/bash
    # Get env variables, since cron's process environment is different than shell's one
    . /etc/environment
    # Run and print all results(except for Spark logs) to stdout
    /data/CMSSpark/bin/cron4rucio_datasets_to_mongo.sh \
      --keytab /etc/secrets/keytab \
      --mongohost mongodb-0.mongodb.datasetmon.svc.cluster.local \
      --mongoport "27017" \
      --mongouser $MONGO_ROOT_USERNAME \
      --mongopass $MONGO_ROOT_PASSWORD \
      --mongowritedb rucio \
      --mongoauthdb admin \
      --nodename $MY_NODE_NAME \
      --sparkport0 $CMSMON_RUCIO_SPARK2MNG_SERVICE_PORT_PORT_0 \
      --sparkport1 $CMSMON_RUCIO_SPARK2MNG_SERVICE_PORT_PORT_1 \
      --sparkbindadr 0.0.0.0 \
      --sparklocalip 127.0.0.1 \
      --wdir $WDIR \
      >> /proc/$(cat /var/run/crond.pid)/fd/1 2>&1
    
    # Create MongoDB indexes after successfull import
    /data/mongosh --host mongodb-0.mongodb.datasetmon.svc.cluster.local \
      --port "27017" --username $MONGO_ROOT_USERNAME --password $MONGO_ROOT_PASSWORD \
      --authenticationDatabase admin </data/cronjob/createindexes.js
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmsmon-rucio-spark2mng
  namespace: datasetmon
  labels:
    app: cmsmon-rucio-spark2mng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cmsmon-rucio-spark2mng
  template:
    metadata:
      labels:
        app: cmsmon-rucio-spark2mng
    spec:
      hostname: cmsmon-rucio-spark2mng
      containers:
        - name: cmsmon-rucio-spark2mng
          image: registry.cern.ch/cmsmonitoring/cmsmon-rucio-spark2mng:v0.0.0
          imagePullPolicy: Always
          env:
            - name: MONGO_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cmsmon-mongo-secrets
                  key: MONGO_ROOT_USERNAME
                  optional: false
            - name: MONGO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cmsmon-mongo-secrets
                  key: MONGO_ROOT_PASSWORD
                  optional: false
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - >
                    export > /etc/environment;
                    chmod +x /data/cronjob/run.sh;
                    echo "30 8  * * * /bin/bash /data/cronjob/run.sh" | crontab -;
          ports:
            - containerPort: 31203 # spark.driver.port
              name: port-0
            - containerPort: 31204 # spark.driver.blockManager.port
              name: port-1
          resources:
            limits:
              cpu: 2000m
              memory: 6Gi
            requests:
              cpu: 500m
              memory: 750Mi
          stdin: true
          tty: true
          volumeMounts:
            - name: cmsmon-mongo-secrets
              mountPath: /etc/secrets
              readOnly: true
            - name: cronjobs-configmap
              mountPath: /data/cronjob
      volumes:
        - name: cmsmon-mongo-secrets
          secret:
            secretName: cmsmon-mongo-secrets
            defaultMode: 0444
        - name: cronjobs-configmap
          configMap:
            name: cm-cmsmon-rucio-spark2mng
