kind: Service
apiVersion: v1
metadata:
  name: spark2mng
  namespace: datasetmon
spec:
  selector:
    app: spark2mng
  type: NodePort
  ports:
    - name: port-0 # spark.driver.port
      nodePort: 31203
      port: 31203
      protocol: TCP
      targetPort: 31203
    - name: port-1 # spark.driver.blockManager.port
      nodePort: 31204
      port: 31204
      protocol: TCP
      targetPort: 31204
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-spark2mng
  namespace: datasetmon
  labels:
    app: spark2mng
data:
  run_spark2hdfs.sh: |
    #!/bin/bash
    . /etc/environment
    echo "Starting run_spark2hdfs.sh ..."
    /data/CMSMonitoring/rucio-dataset-monitoring/spark/cron4rucio_spark2hdfs.sh \
      --keytab /etc/secrets/keytab --hdfs /tmp/cmsmonit/prod \
      --p1 31203 --p2 31204 \
      --host $MY_NODE_NAME --wdir $WDIR
  run_hdfs2mongo.sh: |
    #!/bin/bash
    . /etc/environment
    echo "Starting run_hdfs2mongo.sh ... "
    /data/CMSMonitoring/rucio-dataset-monitoring/spark/cron4rucio_hdfs2mongo.sh \
      --keytab /etc/secrets/keytab --hdfs /tmp/cmsmonit/prod \
      --mongohost "mongodb-0.mongodb.datasetmon.svc.cluster.local" \
      --mongoport "27017" \
      --mongouser $MONGO_ROOT_USERNAME \
      --mongopass $MONGO_ROOT_PASSWORD \
      --mongowritedb rucio \
      --mongoauthdb admin \
      --wdir $WDIR
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: spark2mng
  namespace: datasetmon
spec:
  # UTC
  schedule: "30 07 * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: spark2mng
        spec:
          restartPolicy: Never
          hostname: spark2mng
          containers:
            - name: spark2mng
              image: registry.cern.ch/cmsmonitoring/spark2mng:rgo-0.0.28
              command: [ "/bin/bash", "-c" ]
              args:
                - source /etc/environment;
                  /data/cronjob/run_spark2hdfs.sh && /data/cronjob/run_hdfs2mongo.sh;
                # Restore MongoDB (only)# : /data/cronjob/run_hdfs2mongo.sh;
              env:
                - name: MY_NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                - name: MONGO_ROOT_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: cmsmon-mongo-secrets
                      key: MONGO_ROOT_USERNAME
                      optional: false
                - name: MONGO_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: cmsmon-mongo-secrets
                      key: MONGO_ROOT_PASSWORD
                      optional: false
                - name: K8S_ENV
                  value: "prod"
                - name: PUSHGATEWAY_URL
                  # value: pushgateway.default.svc.cluster.local:9091
                  value: "cms-monitoring:30091"
              ports:
                - containerPort: 31203 # spark.driver.port
                  name: port-0
                - containerPort: 31204 # spark.driver.blockManager.port
                  name: port-1
              lifecycle:
                postStart:
                  exec:
                    command:
                      - "sh"
                      - "-c"
                      - >
                        export > /etc/environment;
              resources:
                limits:
                  cpu: 2000m
                  memory: 6Gi
                requests:
                  cpu: 500m
                  memory: 750Mi
              stdin: true
              tty: true
              volumeMounts:
                - name: cmsmon-mongo-secrets
                  mountPath: /etc/secrets
                  readOnly: true
                - name: cronjobs-configmap
                  mountPath: /data/cronjob
          volumes:
            - name: cmsmon-mongo-secrets
              secret:
                secretName: cmsmon-mongo-secrets
                defaultMode: 0444
            - name: cronjobs-configmap
              configMap:
                name: cm-spark2mng
                defaultMode: 0777
