# Default values for das-mongo-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

environment:

image:
  repository: registry.cern.ch/cmsweb/exporters
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "HG2011h-c"
  command:
  - /data/mongodb_exporter
  - -web.listen-address
  - ":18230"
  - -mongodb.uri
  - "mongodb://das-mongo.das.svc.cluster.local:8230"
  - -mongodb.collect.replset=false
  - -mongodb.collect.oplog=false
  - -mongodb.collect.database
  - "das"
  - -groups.enabled
  - "asserts,durability,background_flushing,connections,extra_info,global_lock,index_counters,network,op_counters,memory,locks,metrics"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: 
prometheus.io/scrape: 'true'
prometheus.io/port: "18230"

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}

initContainers:
- name: checkcouchdb
  image: busybox:1.28
  command: ['sh', '-c', 'until nslookup das-mongo.das; do echo "Waiting for das-mongo"; sleep 10; done;']

ingress:
  enabled: false

resources:
  requests:
    memory: "50Mi"
    cpu: "200m"
  limits:
    memory: "100Mi"
    cpu: "400m"


autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}
