---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 31900
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  replicas: 2
  resources:
    requests:
      memory: 400Mi
  additionalScrapeConfigs:
    name: prometheus-config
    key: prometheus-config.yaml
  serviceMonitorSelector: {}
  # additional configuration can be found in
  # https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec
  remoteWrite:
    - url: http://cms-prometheus.cern.ch:30428/api/v1/write
      queue_config:
        max_samples_per_send: 10000
        max_shards: 30
