kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cpio1
provisioner: kubernetes.io/cinder
parameters:
  type: cpio1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{.Values.quickSetting.namespace}}
  name: {{.Values.db.instance0.pvName}}
spec:
  accessModes:
    - {{.Values.quickSetting.pvc.accessMode}}
  storageClassName: {{.Values.quickSetting.pvc.storageClassName}}
  resources:
    requests:
      storage: {{.Values.quickSetting.pvc.storageSize}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{.Values.quickSetting.namespace}}
  name: {{.Values.db.instance1.pvName}}
spec:
  accessModes:
    - {{.Values.quickSetting.pvc.accessMode}}
  storageClassName: {{.Values.quickSetting.pvc.storageClassName}}
  resources:
    requests:
      storage: {{.Values.quickSetting.pvc.storageSize}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.db.instance2.pvName}}
  namespace: {{.Values.quickSetting.namespace}}
spec:
  accessModes:
    - {{.Values.quickSetting.pvc.accessMode}}
  storageClassName: {{.Values.quickSetting.pvc.storageClassName}}
  resources:
    requests:
      storage: {{.Values.quickSetting.pvc.storageSize}}
---
