kind: Service
apiVersion: v1
metadata:
  name: confdb
  namespace: confdb
spec:
  selector:
    app: confdb
  ports:
    - port: 8340
      targetPort: 8340
      name: confdb
    - port: 18340
      targetPort: 18340
      name: confdb-mon
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: confdb
  name: confdb
  namespace: confdb
spec:
  selector:
    matchLabels:
      app: confdb
  replicas: 1 #PROD# 2
  template:
    metadata:
      labels:
        app: confdb
    spec:
#       hostNetwork: true
#       dnsPolicy: ClusterFirstWithHostNet
      containers:
      - image: cmssw/confdb
        name: confdb
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "3Gi"
            cpu: "1000m"
        ports:
        - containerPort: 8340
          protocol: TCP
          name: confdb
        - containerPort: 18340
          protocol: TCP
          name: confdb-mon
        volumeMounts:
        - name: proxy-secrets
          mountPath: /etc/proxy
          readOnly: true
        - name: secrets
          mountPath: /etc/secrets
          defaultMode: 256
        - name: hostkey
          mountPath: /etc/grid-security/hostkey.pem
          readOnly: true 
        - name: hostcert
          mountPath: /etc/grid-security/hostcert.pem
          readOnly: true 
#PROD#  - name: logs-cephfs
#PROD#    mountPath: /data/srv/logs/confdb
      volumes:
      - name: proxy-secrets
        secret:
          secretName: proxy-secrets
      - name: secrets
        secret:
          secretName: confdb-secrets
      - name: hostkey
        hostPath:
            path: /etc/grid-security/hostkey.pem
            type: File
      - name: hostcert
        hostPath:
            path: /etc/grid-security/hostcert.pem
            type: File
#PROD#- name: logs-cephfs
#PROD#  persistentVolumeClaim:
#PROD#      claimName: logs-cephfs-claim-confdb
