kind: Service
apiVersion: v1
metadata:
  name: couchdb
  namespace: couchdb
spec:
  selector:
    app: couchdb
  ports:
    - port: 5984
      targetPort: 5984
      name: couchdb
    - port: 9984
      targetPort: 9984
      name: couchdb-mon
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: couchdb
  name: couchdb
  namespace: couchdb
spec:
  selector:
    matchLabels:
      app: couchdb
  replicas: 1 #PROD# 1
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
      - image: cmssw/couchdb
        name: couchdb
        tty: true
        stdin: true
        lifecycle:
          postStart:
            exec:
              command:
              - bash
              - -c
              - sudo chmod 0777 /data/srv/state/couchdb/database; sudo chown _couchdb:_couchdb /data/srv/state/couchdb/database
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "3Gi"
            cpu: "2000m"
        ports:
        - containerPort: 5984
          protocol: TCP
          name: couchdb
        - containerPort: 9984
          protocol: TCP
          name: couchdb-mon
        volumeMounts:
        - name: proxy-secrets
          mountPath: /etc/proxy
          readOnly: true
        - name: secrets
          mountPath: /etc/secrets
          defaultMode: 256
        - name: hostkey
          mountPath: /etc/grid-security/hostkey.pem
          readOnly: true 
        - name: hostcert
          mountPath: /etc/grid-security/hostcert.pem
          readOnly: true 
#PROD#  - name: logs-cephfs
#PROD#    mountPath: /data/srv/logs/couchdb
#PROD#  - name: couchdb-storage
#PROD#    mountPath: /data/srv/state/couchdb/database
      volumes:
      - name: proxy-secrets
        secret:
          secretName: proxy-secrets
      - name: secrets
        secret:
          secretName: couchdb-secrets
      - name: hostkey
        hostPath:
            path: /etc/grid-security/hostkey.pem
            type: File
      - name: hostcert
        hostPath:
            path: /etc/grid-security/hostcert.pem
            type: File
#PROD#- name: couchdb-storage
#PROD#  persistentVolumeClaim:
#PROD#      claimName: cephfs-claim-couchdb
#PROD#- name: logs-cephfs
#PROD#  persistentVolumeClaim:
#PROD#      claimName: logs-cephfs-claim-couchdb
