kind: Service
apiVersion: v1
metadata:
  name: das
  namespace: das
spec:
  selector:
    app: das
  ports:
    - port: 8217
      targetPort: 8217
      name: das
    - port: 18217
      targetPort: 18217
      name: das-mon
    - port: 18230
      targetPort: 18230
      name: das-mongo-mon
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: das
  name: das
  namespace: das
spec:
  selector:
    matchLabels:
      app: das
  replicas: 1 #PROD# 3
  template:
    metadata:
      labels:
        app: das
    spec:
      containers:
      - image: cmssw/das
        name: das
        tty: true
        stdin: true
        lifecycle:
          postStart:
            exec:
              command:
              - bash
              - -c
              - sudo chmod 0777 /data/srv/logs/das; sudo chown _das:_das /data/srv/logs/das
        resources:
          requests:
            memory: "500Mi"
            cpu: "2000m"
          limits:
            memory: "3Gi"
            cpu: "4000m"
        ports:
        - containerPort: 8217
          protocol: TCP
          name: das
        - containerPort: 18217
          protocol: TCP
          name: das-mon
        - containerPort: 18230
          protocol: TCP
          name: das-mongo-mon
        volumeMounts:
        - name: proxy-secrets
          mountPath: /etc/proxy
          readOnly: true
        - name: secrets
          mountPath: /etc/secrets
          defaultMode: 256
        - name: hostkey
          mountPath: /etc/grid-security/hostkey.pem
          readOnly: true 
        - name: hostcert
          mountPath: /etc/grid-security/hostcert.pem
          readOnly: true 
#PROD#  - name: logs-cephfs
#PROD#    mountPath: /data/srv/logs/das
#       livenessProbe:
#         httpGet:
#           path: /das/status
#           port: 8217
#         initialDelaySeconds: 3
#         periodSeconds: 3
      volumes:
      - name: proxy-secrets
        secret:
          secretName: proxy-secrets
      - name: secrets
        secret:
          secretName: das-secrets
      - name: hostkey
        hostPath:
            path: /etc/grid-security/hostkey.pem
            type: File
      - name: hostcert
        hostPath:
            path: /etc/grid-security/hostcert.pem
            type: File
#PROD#- name: logs-cephfs
#PROD#  persistentVolumeClaim:
#PROD#      claimName: logs-cephfs-claim-das
