kind: Service
apiVersion: v1
metadata:
  name: dqmgui
  namespace: dqm
spec:
  selector:
    app: dqmgui
  ports:
    - port: 8060
      targetPort: 8060
      name: dqmgui-dev
    - port: 8081
      targetPort: 8081
      name: dqmgui-relval
    - port: 8080
      targetPort: 8080
      name: dqmgui-offline
    - port: 18060
      targetPort: 18060
      name: dqmgui-mon
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: dqmgui
  name: dqmgui
  namespace: dqm
spec:
  selector:
    matchLabels:
      app: dqmgui
  replicas: 1 #PROD# 1
  template:
    metadata:
      labels:
        app: dqmgui
    spec:
      containers:
      - image: cmssw/dqmgui
        name: dqmgui
        tty: true
        stdin: true
#         lifecycle:
#           postStart:
#             exec:
#               command:
#               - bash
#               - -c
#               - sudo chmod 0777 /data/srv/state/dqmgui/data; sudo chown _dqmgui:_dqmgui /data/srv/state/dqmgui/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "3Gi"
            cpu: "1000m"
        ports:
        - containerPort: 8060
          protocol: TCP
          name: dqmgui-dev
        - containerPort: 8081
          protocol: TCP
          name: dqmgui-relval
        - containerPort: 8080
          protocol: TCP
          name: dqmgui-offline
        - containerPort: 18060
          protocol: TCP
          name: dqmgui-mon
        volumeMounts:
        - name: proxy-secrets
          mountPath: /etc/proxy
          readOnly: true
        - name: secrets
          mountPath: /etc/secrets
          defaultMode: 256
        - name: hostkey
          mountPath: /etc/grid-security/hostkey.pem
          readOnly: true 
        - name: hostcert
          mountPath: /etc/grid-security/hostcert.pem
          readOnly: true 
#PROD#  - name: dqmgui-storage
#PROD#    mountPath: /data/srv/state/dqmgui/data
#PROD#  - name: logs-cephfs
#PROD#    mountPath: /data/srv/logs/dqmgui
      volumes:
      - name: proxy-secrets
        secret:
          secretName: proxy-secrets
      - name: secrets
        secret:
          secretName: dqmgui-secrets
      - name: hostkey
        hostPath:
            path: /etc/grid-security/hostkey.pem
            type: File
      - name: hostcert
        hostPath:
            path: /etc/grid-security/hostcert.pem
            type: File
#PROD#- name: dqmgui-storage
#PROD#  persistentVolumeClaim:
#PROD#      claimName: dqmgui-claim
#PROD#- name: logs-cephfs
#PROD#  persistentVolumeClaim:
#PROD#      claimName: logs-cephfs-claim-dqm
