apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-das
  namespace: das
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ include "list.whitelist" . | quote  }}
spec:
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: /das
        pathType: Prefix
        backend:
          service:
            name: das-server
            port: 
              number: 8217
