apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-ruciocm
  namespace: ruciocm
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ include "list.whitelist" . | quote  }}
spec:
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: /rucioconmon
        pathType: Prefix
        backend:
          service:
            name: monitor
            port: 
              number: 8400
