FROM almalinux:minimal
# this image does not contain neither yum nor dnf

#RUN dnf -y update && \
#    dnf -y install  curl libcurl vim python3-pycurl pip sudo less && \
#    dnf clean all
#RUN yum update -y && \
#    yum install -y --skip-broken curl libcurl vim python3-pycurl pip sudo less \
#    && yum clean all && rm -rf /var/cache/yum
