---
environment: "test"

image:
  tag: "v3.240809-stable"

# disable liveness/readiness
# https://helm.sh/docs/chart_template_guide/values_files/#deleting-a-default-key
livenessProbePreProd: null
readinessProbePreProd: null
livenessProbeTest: null
readinessProbeTest: null
livenessProbe: null
readinessProbe: null
