# Default values for crabserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

enabled: true

replicaCount:
  prod: 15
  preprod: 1
  test: 1

image:
  path: registry.cern.ch/cmscrab/crabserver
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v3.231006"
  command:
  - /bin/bash
  - /opt/config/setup.sh
  env:
  - name: CRABSERVER_LOGSTDOUT
    value: "t"
  - name: CRABSERVER_THREAD_POOL
    value: "2"

canary:
  enabled: false
  image:
    path: registry.cern.ch/cmscrab/crabserver
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "v3.231006"
    command:
    - /bin/bash
    - /opt/config/setup.sh
    env:
    - name: CRABSERVER_LOGSTDOUT
      value: "t"
    - name: CRABSERVER_THREAD_POOL
      value: "2"

environment:

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations:
  prometheus.io/scrape: 'true'
  prometheus.io/port: "18270"

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 2000

imageFilebeatSecurityContext:
  allowPrivilegeEscalation: false

securityContext:
  privileged: true

serviceMon:
  name: crabserver-mon
  port: 18720
  protocol: TCP

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"

resources:
  limits:
    cpu: 1500m
    memory: 3Gi
  requests:
    cpu: 200m
    memory: 256Mi

livenessProbe:
  exec:
    command:
    - /bin/sh
    - -c
    - |
      cmsweb-ping --url=http://localhost:8270/crabserver/prod/info --authz=/etc/hmac/hmac -verbose 0 | egrep "^[2-4]"
  failureThreshold: 3
  initialDelaySeconds: 120
  periodSeconds: 60
  timeoutSeconds: 60

readinessProbe:
  exec:
    command:
    - /bin/sh
    - -c
    - |
      cmsweb-ping --url=http://localhost:8270/crabserver/prod/info --authz=/etc/hmac/hmac -verbose 0 | egrep "^[2-4]"
  periodSeconds: 60
  timeoutSeconds: 60

livenessProbePreProd:
  exec:
    command:
    - /bin/sh
    - -c
    - |
      cmsweb-ping --url=http://localhost:8270/crabserver/preprod/info --authz=/etc/hmac/hmac -verbose 0 | egrep "^[2-4]"
  failureThreshold: 3
  initialDelaySeconds: 120
  periodSeconds: 60
  timeoutSeconds: 60

readinessProbePreProd:
  exec:
    command:
    - /bin/sh
    - -c
    - |
      cmsweb-ping --url=http://localhost:8270/crabserver/preprod/info --authz=/etc/hmac/hmac -verbose 0 | egrep "^[2-4]"
  periodSeconds: 60
  timeoutSeconds: 60

livenessProbeTest:
  exec:
    command:
    - /bin/sh
    - -c
    - |
      cmsweb-ping --url=http://localhost:8270/crabserver/dev/info --authz=/etc/hmac/hmac -verbose 0 | egrep "^[2-4]"
  failureThreshold: 3
  initialDelaySeconds: 120
  periodSeconds: 60
  timeoutSeconds: 60

readinessProbeTest:
  exec:
    command:
    - /bin/sh
    - -c
    - |
      cmsweb-ping --url=http://localhost:8270/crabserver/dev/info --authz=/etc/hmac/hmac -verbose 0 | egrep "^[2-4]"
  periodSeconds: 60
  timeoutSeconds: 60

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}


ciServiceAccount:
  enabled: false

logPipeline:
  enabled: false
  filebeat:
    name: filebeat
    path: docker.elastic.co/beats/filebeat:8.5.1
    policy: IfNotPresent
    args:
    - bash
    - -c
    - filebeat -c /etc/filebeat.yml --path.data /data/filebeat/${MY_NODE_NAME}/data -e
    env:
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: MY_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    resources:
      requests:
        memory: "128Mi"
        cpu: "200m"
      limits:
        cpu: "1"
        memory: "1Gi"
