FROM debian:stable-slim as tools
RUN apt-get update && apt-get -y install curl
ENV WDIR=/data/tools
WORKDIR $WDIR
# download mongodb tools
ENV MONGO_VER=debian92-x86_64-100.8.0
RUN curl -ksLO https://fastdl.mongodb.org/tools/db/mongodb-database-tools-$MONGO_VER.tgz \
    && tar xfz mongodb-database-tools-$MONGO_VER.tgz \
    && rm mongodb-database-tools-$MONGO_VER.tgz \
    && mv mongodb-database-tools-$MONGO_VER/bin . \
    && rm -rf mongodb-database-tools-$MONGO_VER
RUN mv bin/* . && rm -rf bin
# download sops tool
ENV SOPS_VER=v3.8.0
RUN curl -ksLO https://github.com/getsops/sops/releases/download/${SOPS_VER}/sops-${SOPS_VER}.linux.amd64
RUN mv sops-${SOPS_VER}.linux.amd64 sops && chmod +x sops
# download age tool
ENV AGE_VER=v1.1.1
RUN curl -ksLO https://github.com/FiloSottile/age/releases/download/v1.1.1/age-${AGE_VER}-linux-amd64.tar.gz
RUN tar xfz age-${AGE_VER}-linux-amd64.tar.gz
RUN mv age agetools && mv agetools/age . && mv agetools/age-keygen . && rm -rf age-${AGE_VER}-linux-amd64.tar.gz agetools
#Get alert manager
RUN curl -ksLO https://github.com/prometheus/alertmanager/releases/download/v0.24.0/alertmanager-0.24.0.linux-amd64.tar.gz
RUN tar xfz alertmanager-0.24.0.linux-amd64.tar.gz && mv alertmanager-0.24.0.linux-amd64/amtool $WDIR/ && rm -rf alertmanager-0.24.0.linux-amd64*

# main mongodb image
FROM mongo:5.0.15
WORKDIR /root
ENV MONGODB_ID mongo-0

RUN apt update
RUN apt install -y iproute2 && apt-get -y install krb5-user && apt-get install -y cron

COPY --from=tools /data/tools /data/tools
COPY /startup-script-mongo /root

#add kinit operation
ADD run.sh /root/run.sh

#add cronjob


#add mongotools
COPY /mongotools /data/tools

COPY copy_cron.sh /data/tools/copy_cron.sh
COPY mongo-prod.cron /data/tools/mongo-prod.cron
COPY mongo-preprod.cron /data/tools/mongo-preprod.cron
COPY mongo-test.cron /data/tools/mongo-test.cron


ENV PATH=/data/tools:$PATH

CMD ["/bin/sh", "-c", "./run.sh; /data/tools/copy_cron.sh; ./startup-$MONGODB_ID.sh;"]

