apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ing-auth
  namespace: auth
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
  - host: cmsweb-auth.cern.ch
    http:
      paths:
      - path: /
        backend:
          serviceName: auth-proxy-server
          servicePort: 443
  tls:
  - hosts:
    - cmsweb-auth.cern.ch
  secretName: auth-secrets
