# cmsmon-hadoop-base:spark3-YYYYMMDD
# Build by CMSSpark GH actions
FROM gitlab-registry.cern.ch/db/cerndb-infra-hadoop-conf:latest-hdp3
MAINTAINER Ceyhun Uzunoglu ceyhunuzngl@gmail.com

# Should be full such that includes minor version
ARG PY_VERSION=3.9.13

ENV WDIR=/data
WORKDIR $WDIR
ENV PATH $PATH:/usr/hdp/hadoop/bin:/usr/hdp/sqoop/bin
ENV PATH $PATH:/data

# add necessary RPMs
RUN yum install -y fetch-crl git-core zip unzip which file bzip2 sudo openssl openssl-devel openssl-libs openssh \
        wget make openssh-clients python-backports-ssl_match_hostname cmake shibboleth log4shib xmltooling-schemas \
        opensaml-schemas libaio libaio-devel net-tools lsof bind-utils initscripts patch python-pip libffi-devel gcc \
        bzip2-devel zlib-devel && \
    yum clean all && rm -rf /var/cache/yum && \
# Build Python3
    wget https://www.python.org/ftp/python/${PY_VERSION}/Python-${PY_VERSION}.tgz && \
    tar -xvf Python-${PY_VERSION}.tgz && \
    cd Python-${PY_VERSION} && \
    ./configure --enable-optimizations && \
    make altinstall && \
    export PY_MAJOR=$(echo ${PY_VERSION%.*}) && \
    rm -f /usr/bin/python3 && ln -s /usr/local/bin/python${PY_MAJOR} /usr/bin/python3 && \
    rm -f /usr/bin/pip3 && ln -s /usr/local/bin/pip${PY_MAJOR} /usr/bin/pip3 && \
    python3 -m pip install --upgrade pip && \
    cd $WDIR && \
    rm -rf Python-${PY_VERSION}.tgz Python-${PY_VERSION} && \
    unset PY_MAJOR && \
# Python build done
    hadoop-set-default-conf.sh analytix && \
    source hadoop-setconf.sh analytix 3.2 spark3 && \
    touch /etc/hadoop/conf/topology.table.file && ln -s /bin/bash /usr/bin/bashs && \
    cp /usr/hdp/spark3/kubernetes/dockerfiles/spark/entrypoint.sh /usr/bin/entrypoint.sh && \
    echo "32 */6 * * * root ! /usr/sbin/fetch-crl -q -r 360" >/etc/cron.d/fetch-crl-docker
# add fetch-crl to fetch all certificates

# start the setup
WORKDIR ${WDIR}
