kind: Service
apiVersion: v1
metadata:
  name: cmsmon-rucio-ds
  namespace: hdfs
spec:
  selector:
    app: cmsmon-rucio-ds
  type: NodePort
  ports:
    - name: port-0 # spark.driver.port, cern default is 5201
      nodePort: 31201
      port: 31201
      protocol: TCP
      targetPort: 31201
    - name: port-1 # spark.driver.blockManager.port
      nodePort: 31202
      port: 31202
      protocol: TCP
      targetPort: 31202
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cmsmon-rucio-ds
  namespace: hdfs
  labels:
    app: cmsmon-rucio-ds
# Reference: https://www.ibm.com/support/pages/cron-environment-and-cron-job-failures
data:
  run.sh: |
    #!/bin/bash
    # Get env variables, since cron's process environment is different than shell's one
    . /etc/environment
    # For test, change to "--amq /etc/secrets/amq_broker_training.json" and put "--test" param
    # Run and print all results(except for Spark logs) to stdout
    /data/CMSSpark/bin/cron4rucio_datasets_daily_stats.sh \
      --keytab /etc/secrets/keytab \
      --cmsr /etc/secrets/cmsr_cstring \
      --rucio /etc/secrets/rucio \
      --amq /etc/secrets/amq_broker.json \
      --cmsmonitoring /data/CMSMonitoring.zip \
      --stomp /data/stomp-v700.zip \
      --eos /eos/user/c/cmsmonit/www/rucio_daily_ds_stats \
      --p1 31201 --p2 31202 --host $MY_NODE_NAME --wdir $WDIR \
      >> /proc/$(cat /var/run/crond.pid)/fd/1 2>&1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmsmon-rucio-ds
  namespace: hdfs
  labels:
    app: cmsmon-rucio-ds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cmsmon-rucio-ds
  template:
    metadata:
      labels:
        app: cmsmon-rucio-ds
    spec:
      hostname: cmsmon-rucio-ds
      containers:
        - name: cmsmon-rucio-ds
          image: registry.cern.ch/cmsmonitoring/cmsmon-spark:v0.4.0.5
          imagePullPolicy: Always
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_ENV
              value: "prod"
            - name: PUSHGATEWAY_URL
              value: "pushgateway.default.svc.cluster.local:9091"
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - >
                    export > /etc/environment;
                    chmod +x /data/cronjob/run.sh;
                    echo "45 6  * * * /bin/bash /data/cronjob/run.sh" | crontab -;
          ports:
            - containerPort: 31201 # spark.driver.port
              name: port-0
            - containerPort: 31202 # spark.driver.blockManager.port
              name: port-1
          resources:
            limits:
              cpu: 2000m
              memory: 6Gi
            requests:
              cpu: 500m
              memory: 750Mi
          stdin: true
          tty: true
          volumeMounts:
            - name: rucio-daily-stats-secrets
              mountPath: /etc/secrets
              readOnly: true
            - name: eos # EOS access
              mountPath: /eos
              mountPropagation: HostToContainer
            - name: cronjobs-configmap
              mountPath: /data/cronjob
      volumes:
        - name: rucio-daily-stats-secrets
          secret:
            secretName: rucio-daily-stats-secrets
        - name: eos
          hostPath:
            path: /var/eos
        - name: cronjobs-configmap
          configMap:
            name: cmsmon-rucio-ds
