kind: ConfigMap
apiVersion: v1
metadata:
  name: cron-spark-jobs
  namespace: hdfs
  labels:
    app: cron-spark-jobs
data:
  # Setup script for short named env variables
  s.sh: |
    . /etc/environment
    # Base run path
    export B_=$WDIR/CMSSpark/bin
    # Shared args
    export A_=" --keytab /etc/secrets/keytab --host ${MY_NODE_NAME} --wdir ${WDIR} --p1 32500 --p2 32501 "
    # CMSPOPDB keytab args
    export POPDB_A_=" --keytab /etc/secrets/cmspopdb-keytab --host ${MY_NODE_NAME} --wdir ${WDIR} --p1 32500 --p2 32501 "
    # Stdout of crond
    export O_=/proc/$(cat /var/run/crond.pid)/fd/1
    export EOS_=$BASE_EOS_OUT
  crons.txt: |
    # MONTHLY
    00 16 03  *  * . /data/cronjob/s.sh; $B_/cron4hpc_at_cms.sh        $A_ --output $EOS_/hpc                >>$O_ 2>&1
    00 16 05  *  * . /data/cronjob/s.sh; $B_/cron4crab_popularity.sh   $A_ --output $EOS_/crabPop/data       >>$O_ 2>&1
    00 16 07  *  * . /data/cronjob/s.sh; $B_/cron4gen_crsg_plots.sh    $A_ --output $EOS_/EventCountPlots    >>$O_ 2>&1
    00 16 19  *  * . /data/cronjob/s.sh; $B_/cron4hs06_cputime_plot.sh $A_ --output $EOS_/hs06cputime        >>$O_ 2>&1
    00 16 24  *  * . /data/cronjob/s.sh; $B_/cron4eos_dataset.sh       $A_ --output $EOS_/EOS/data           >>$O_ 2>&1
    00 16 27  *  * . /data/cronjob/s.sh; $B_/cron4crab_unique_users.sh $A_ --output $EOS_/crab_uu            >>$O_ 2>&1
    # DAILY
    07 08  *  *  * . /data/cronjob/s.sh; $B_/cron4rucio_daily.sh       $POPDB_A_ --output /cms/rucio_daily   >>$O_ 2>&1
---
kind: Service
apiVersion: v1
metadata:
  name: cron-spark-jobs
  namespace: hdfs
spec:
  selector:
    app: cron-spark-jobs
  type: NodePort
  ports:
    - name: port-0
      nodePort: 32500
      port: 32500
      protocol: TCP
      targetPort: 32500
    - name: port-1
      nodePort: 32501
      port: 32501
      protocol: TCP
      targetPort: 32501
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron-spark-jobs
  namespace: hdfs
  labels:
    app: cron-spark-jobs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cron-spark-jobs
  template:
    metadata:
      labels:
        app: cron-spark-jobs
    spec:
      hostname: cron-spark-jobs
      containers:
        - name: cron-spark-jobs
          image: registry.cern.ch/cmsmonitoring/cmsmon-spark:v0.4.0.22
          imagePullPolicy: Always
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_ENV
              value: "prod"
            - name: BASE_EOS_OUT
              value: "/eos/user/c/cmsmonit/www"
            - name: PUSHGATEWAY_URL
              value: "pushgateway.default.svc.cluster.local:9091"
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - >
                    export > /etc/environment;
                    crontab < /data/cronjob/crons.txt;
          ports:
            - containerPort: 32500
              name: port-0
            - containerPort: 32501
              name: port-1
          resources:
            limits:
              cpu: 2000m
              memory: 6Gi
            requests:
              cpu: 500m
              memory: 750Mi
          stdin: true
          tty: true
          volumeMounts:
            - name: cron-spark-jobs-secrets
              mountPath: /etc/secrets
              readOnly: true
            - name: eos
              mountPath: /eos
              mountPropagation: HostToContainer
            - name: cron-spark-jobs-configmap
              mountPath: /data/cronjob
      volumes:
        - name: cron-spark-jobs-secrets
          secret:
            secretName: cron-spark-jobs-secrets
        - name: eos
          hostPath:
            path: /var/eos
        - name: cron-spark-jobs-configmap
          configMap:
            name: cron-spark-jobs
