# Ref: kubernetes/cmsweb/services/cert-checker.yaml
kind: Service
apiVersion: v1
metadata:
  name: http-exporter-certcheck
  namespace: http
spec:
  type: ClusterIP
  ports:
    - port: 8888
      protocol: TCP
      name: http
  selector:
    app: http-exporter-certcheck
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: http-exporter-certcheck
  namespace: http
  labels:
    app: http-exporter-certcheck
data:
  configs.json: |
    [
      {"cert": "/etc/secrets/cmsmonit_cert", "ckey": "/etc/secrets/cmsmonit_key"},
      {"cert": "/etc/secrets/cms_monitoring_cert", "ckey": "/etc/secrets/cms_monitoring_key"},
      {"cert": "/etc/secrets/cms_dm_monitoring_cert", "ckey": "/etc/secrets/cms_dm_monitoring_key"},
      {"cert": "/etc/secrets/robot-training-cert.pem", "ckey": "/etc/secrets/robot-training-key.pem"},
      {"keytab": "/etc/secrets/cmsmonit_keytab"},
      {"keytab": "/etc/secrets/cmssqoop_keytab"}
    ]
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: http-exporter-certcheck
  name: http-exporter-certcheck
  namespace: http
spec:
  selector:
    matchLabels:
      app: http-exporter-certcheck
  replicas: 1
  template:
    metadata:
      labels:
        app: http-exporter-certcheck
        env: k8s #k8s#
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8888"
    spec:
      containers:
        - image: registry.cern.ch/cmsmonitoring/cert-checker:20221207
          name: http-exporter-certcheck
          command:
            - /data/cert-checker
            - -config
            - /etc/config/configs.json
            - -team
            - "cmsmon"
            - -httpPort
            - "8888"
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8888
            initialDelaySeconds: 3
            periodSeconds: 600
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          ports:
            - containerPort: 8888
          volumeMounts:
            - name: robot-secrets
              mountPath: /etc/robots
              readOnly: true
            - name: certcheck-secrets
              mountPath: /etc/secrets
              readOnly: true
            - name: http-exporter-certcheck-configmap
              mountPath: /etc/config
      volumes:
        - name: robot-secrets
          secret:
            secretName: robot-secrets
        - name: certcheck-secrets
          secret:
            secretName: certcheck-secrets
        - name: http-exporter-certcheck-configmap
          configMap:
            name: http-exporter-certcheck
