kind: Service
apiVersion: v1
metadata:
  name: http-exporter-mcm
  namespace: http
spec:
  type: ClusterIP
  ports:
  - port: 18006
    protocol: TCP
    name: http
  selector:
    app: http-exporter-mcm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-exporter-mcm
  namespace: http
  labels:
     app: http-exporter-mcm
spec:
   replicas: 1
   selector:
     matchLabels:
       app: http-exporter-mcm
   template:
      metadata:
         labels:
           app: http-exporter-mcm
      spec:
        containers:
        - args:
          - /data/http_exporter
          - -uri
          - "https://cms-pdmv.cern.ch/mcm/"
          - -namespace
          - "mcm"
          - -proxyfile
          - /etc/proxy/proxy
          - -port
          - ":18006"
          - -agent
          - "monitoring"
          - -verbose
          name: http-exporter-mcm
          image: registry.cern.ch/cmsmonitoring/http-exporter:20230321
          ports:
          - containerPort: 18006
          volumeMounts:
          - name: proxy-secrets
            mountPath: /etc/proxy
            readOnly: true
        volumes:
        - name: proxy-secrets
          secret:
            secretName: proxy-secrets
