kind: Service
apiVersion: v1
metadata:
  name: http-exporter-rucio
  namespace: http
spec:
  type: ClusterIP
  ports:
  - port: 18011
    protocol: TCP
    name: http
  selector:
    app: http-exporter-rucio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-exporter-rucio
  namespace: http
  labels:
     app: http-exporter-rucio
spec:
   replicas: 1
   selector:
     matchLabels:
       app: http-exporter-rucio
   template:
      metadata:
         labels:
           app: http-exporter-rucio
      spec:
        containers:
        - args:
          - /data/http_exporter
          - -uri
          - "http://cms-rucio.cern.ch/ping"
          - -namespace
          - "rucio"
          - -port
          - ":18011"
          - -agent
          - "monitoring"
          - -renewClientInterval
          - "600"
          - -verbose
          name: http-exporter-rucio
          image: registry.cern.ch/cmsmonitoring/http-exporter:20230321
          ports:
          - containerPort: 18011
