apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: das-share
  namespace: das
provisioner: manila-provisioner
parameters:
  type: "Meyrin CephFS"
  zones: nova
  osSecretName: os-trustee
  osSecretNamespace: kube-system
  protocol: CEPHFS
  backend: csi-cephfs
  csi-driver: cephfs.csi.ceph.com
  # find osShareID from manila list for your share, e.g. das-share
  osShareID: aa8c09d9-7ab3-4436-afdc-8198375d0a72
  # find osShareAccessID from manila access-list das-share
  osShareAccessID: 155b7a79-2436-481e-933e-1a4e743d04a7
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-claim-das
  namespace: das
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8G
  storageClassName: das-share
