---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-claim-cric
  namespace: auth
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1G
  storageClassName: geneva-cephfs-testing
