apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: default-share
  namespace: default
provisioner: manila-provisioner
parameters:
  type: "Meyrin CephFS"
  zones: nova
  osSecretName: os-trustee
  osSecretNamespace: kube-system
  protocol: CEPHFS
  backend: csi-cephfs
  csi-driver: cephfs.csi.ceph.com
  osShareID: d39837fe-67c9-4440-9f37-6a6bbbf60494
  osShareAccessID: 955321c0-2af2-40fc-bc60-5e3b7cdb9746
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-cephfs-claim-preprod-default
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 22G
  storageClassName: default-share

