# CephFS volume claims:
# for production storage use
#   storageClassName: meyrin-cephfs
# for test storage use
#   storageClassName: geneva-cephfs-testing
# ---
#
# frontend storage claim
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-cephfs-claim
  namespace: default # this may change if I move FE to dedicated ns
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: meyrin-cephfs
# ---
#
# ConfDB storage claim
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-cephfs-claim
  namespace: confdb
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: meyrin-cephfs
---
#
# CouchDB storage claim
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-cephfs-claim
  namespace: couchdb
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: meyrin-cephfs
---
#
# CRAB space storage claim
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-cephfs-claim
  namespace: crab
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: meyrin-cephfs
---
#
# DAS storage claim
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-cephfs-claim
  namespace: das
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: meyrin-cephfs
---
#
# DBS storage claim
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-cephfs-claim
  namespace: dbs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: meyrin-cephfs
---
#
# DQM storage claim
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-cephfs-claim
  namespace: dqm
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: meyrin-cephfs
---
#
# DMWM storage claim
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-cephfs-claim
  namespace: dmwm
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: meyrin-cephfs
---
#
# Phedex storage claim
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-cephfs-claim
  namespace: phedex
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: meyrin-cephfs
---
#
# T0 storage claim
#
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-cephfs-claim
  namespace: tzero
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: meyrin-cephfs
