kind: Service
apiVersion: v1
metadata:
  name: acdcserver
  namespace: dmwm
spec:
  selector:
    app: acdcserver
  ports:
    - port: 5984
      targetPort: 5984
      name: acdcserver
    - port: 15984
      targetPort: 15984
      name: acdcserver-mon
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: acdcserver
  name: acdcserver
  namespace: dmwm
spec:
  selector:
    matchLabels:
      app: acdcserver
  replicas: 1
  template:
    metadata:
      labels:
        app: acdcserver
    spec:
#       hostNetwork: true
#       dnsPolicy: ClusterFirstWithHostNet
      containers:
      - image: cmssw/acdcserver
        name: acdcserver
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "3Gi"
            cpu: "1000m"
        ports:
        - containerPort: 5984
          protocol: TCP
          name: acdcserver
        - containerPort: 15984
          protocol: TCP
          name: acdcserver-mon
        volumeMounts:
        - name: proxy-secrets
          mountPath: /etc/proxy
          readOnly: true
        - name: secrets
          mountPath: /etc/secrets
          defaultMode: 256
        - name: hostkey
          mountPath: /etc/grid-security/hostkey.pem
          readOnly: true 
        - name: hostcert
          mountPath: /etc/grid-security/hostcert.pem
          readOnly: true 
#PROD#  - name: logs-cephfs
#PROD#    mountPath: /data/srv/logs/acdcserver
      initContainers:
      - name: checkcouchdb
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup couchdb.couchdb; do echo "Waiting for couchdb"; sleep 10; done;']
      volumes:
      - name: proxy-secrets
        secret:
          secretName: proxy-secrets
      - name: secrets
        secret:
          secretName: acdcserver-secrets
      - name: hostkey
        hostPath:
            path: /etc/grid-security/hostkey.pem
            type: File
      - name: hostcert
        hostPath:
            path: /etc/grid-security/hostcert.pem
            type: File
#PROD#- name: logs-cephfs
#PROD#  persistentVolumeClaim:
#PROD#      claimName: logs-cephfs-claim-dmwm
