kind: Service
apiVersion: v1
metadata:
  name: auth-proxy-server
  namespace: auth
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  - port: 9091
    targetPort: 9091
    protocol: TCP
    name: metrics
  selector:
    app: auth-proxy-server