kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: udp-server
  name: udp-server
spec:
  selector:
    matchLabels:
      app: udp-server
  replicas: 1
  template:
    metadata:
      labels:
        app: udp-server
    spec:
      tolerations:
      - key: "udp-server"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - image: registry.cern.ch/cmsmonitoring/udp-server:v0.0.4
        name: udp-server
        args:
          - /data/udp_server
          - -config=/etc/secrets/udp_server.json
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "3Gi"
            cpu: "1000m"
        ports:
        - containerPort: 9331
          protocol: UDP
          name: udp
          hostPort: 9331
        - containerPort: 9330
          protocol: TCP
          name: health
        volumeMounts:
        - name: udp-secrets
          mountPath: /etc/secrets
        livenessProbe:
          httpGet:
            path: /health
            port: 9330
          initialDelaySeconds: 10
          periodSeconds: 60
      volumes:
      - name: udp-secrets
        secret:
          secretName: udp-secrets
---
